### ISSUE TITLE
Implement missing data generation function

### ISSUE THREAD

**Issue by gabrielziegler3** [gabrielziegler3/research-topics-missing-data#2]
Create functions to create missing data for different columns with different proportions

**Comment by victoriatascau** [comment]
- [x]  generate missing data in x/0/0 proportion, 0/x/0 proportion, 0/0/x proportion for MCAR, MAR, MNAR, where x = [three values, let's say 5, 10, 30]
- [x] apply the metrics we agreed on on this amputated data set
